cor_all_pe <- read.table(file='all_pe.cor_all.tsv', sep=' ')
cor_all_sr <- read.table(file='all_sr.cor_all.tsv', sep=' ')
dem_all_pe <- read.table(file='all_pe.dem_all.tsv', sep=' ')
dem_all_sr <- read.table(file='all_sr.dem_all.tsv', sep=' ')
fault_dem_pe <- read.table(file='all_pe.fault_dem.tsv', sep=' ')
fault_dem_sr <- read.table(file='all_sr.fault_dem.tsv', sep=' ')
cor_all_pe.matrix <- as.matrix(cor_all_pe)
cor_all_sr.matrix <- as.matrix(cor_all_sr)
dem_all_pe.matrix <- as.matrix(dem_all_pe)
dem_all_sr.matrix <- as.matrix(dem_all_sr)
fault_dem_pe.matrix <- as.matrix(fault_dem_pe)
fault_dem_sr.matrix <- as.matrix(fault_dem_sr)
colnames(cor_all_pe.matrix) <- c("sampleNr", "GBSX_GBS", "GBSX_RAD", "GBSX_NAN", "Stacks_rad", "Stacks_short")
colnames(cor_all_sr.matrix) <- c("sampleNr", "GBSX_GBS", "GBSX_RAD", "GBSX_NAN", "Stacks_rad", "Stacks_short")
colnames(dem_all_pe.matrix) <- c("sampleNr", "GBSX_GBS", "GBSX_RAD", "GBSX_NAN", "Stacks_rad", "Stacks_short")
colnames(dem_all_sr.matrix) <- c("sampleNr", "GBSX_GBS", "GBSX_RAD", "GBSX_NAN", "Stacks_rad", "Stacks_short")
colnames(fault_dem_pe.matrix) <- c("sampleNr", "GBSX_GBS", "GBSX_RAD", "GBSX_NAN", "Stacks_rad", "Stacks_short")
colnames(fault_dem_sr.matrix) <- c("sampleNr", "GBSX_GBS", "GBSX_RAD", "GBSX_NAN", "Stacks_rad", "Stacks_short")
cor_all_pe.cor.matrix <- cor_all_pe.matrix[,-1]
cor_all_sr.cor.matrix <- cor_all_sr.matrix[,-1]
dem_all_pe.cor.matrix <- dem_all_pe.matrix[,-1]
dem_all_sr.cor.matrix <- dem_all_sr.matrix[,-1]
fault_dem_pe.cor.matrix <- fault_dem_pe.matrix[,-1]
fault_dem_sr.cor.matrix <- fault_dem_sr.matrix[,-1]
setEPS()
postscript("paired_boxplots.eps")
layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))
boxplot(as.data.frame(dem_all_pe.cor.matrix), main="Paired Percentage Demultiplex")
boxplot(as.data.frame(cor_all_pe.cor.matrix), main="Paired Percentage Correct Trimmed")
boxplot(as.data.frame(fault_dem_pe.cor.matrix), main="Paired Percentage Fault")
dev.off()
setEPS()
postscript("signle_boxplots.eps")
layout(matrix(c(1,1,2,3), 2, 2, byrow = TRUE))
boxplot(as.data.frame(dem_all_sr.cor.matrix), main="Signle Percentage Demultiplex")
boxplot(as.data.frame(cor_all_sr.cor.matrix), main="Signle Percentage Correct Trimmed")
boxplot(as.data.frame(fault_dem_sr.cor.matrix), main="Signle Percentage Fault")
dev.off()
mean_matrix = matrix(c(mean(dem_all_pe.cor.matrix[,1]), mean(cor_all_pe.cor.matrix[,1]), mean(dem_all_sr.cor.matrix[,1]), mean(cor_all_sr.cor.matrix[,1]), mean(dem_all_pe.cor.matrix[,2]), mean(cor_all_pe.cor.matrix[,2]), mean(dem_all_sr.cor.matrix[,2]), mean(cor_all_sr.cor.matrix[,2]), mean(dem_all_pe.cor.matrix[,3]), mean(cor_all_pe.cor.matrix[,3]), mean(dem_all_sr.cor.matrix[,3]), mean(cor_all_sr.cor.matrix[,3]), mean(dem_all_pe.cor.matrix[,4]), mean(cor_all_pe.cor.matrix[,4]), mean(dem_all_sr.cor.matrix[,4]), mean(cor_all_sr.cor.matrix[,4]), mean(dem_all_pe.cor.matrix[,5]), mean(cor_all_pe.cor.matrix[,5]), mean(dem_all_sr.cor.matrix[,5]), mean(cor_all_sr.cor.matrix[,5])), ncol=5, nrow=4)
layout(matrix(c(1,1,1,1), 1,1, byrow = TRUE))
colnames(mean_matrix) <- c("GBSX_GBS", "GBSX_RAD", "GBSX_NAN", "Stacks_RAD", "Stacks_short")
rownames(mean_matrix) <- c("Paired end demultiplex", "Paired end correct trimmed", "Signle read demultiplex", "Signle end correct trimmed")
setEPS()
postscript("complete_barplot.eps")
par(mar=c(11.5,4.1,8,3), xpd=TRUE)
barplot(mean_matrix, main="GBSX vs Stacks", beside=TRUE, col=c("gray1", "gray25", "gray50", "gray75"), las=2)
legend("bottom", inset=c(0,-0.7), legend=rownames(mean_matrix), fill=c("gray1", "gray25", "gray50", "gray75"))
dev.off()
